spring:
  application:
    name: ms-event-category
  datasource:
    url: jdbc:mysql://localhost:3306/world_dance_events_modality
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /api/v1/actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 9091
  servlet:
    context-path: /api/v1

security:
  jwt:
    secret-key: ${JWT_SECRET:F0bVQgRnuk6DRxooVWKaG0ndlgqEeI/4YXObXeOaR2Q=}